---
- name: Create group
  group:
    name: "{{ service.group }}"
    system: yes
    state: present

- name: Create user
  user:
    name: "{{ service.user }}"
    group: "{{ service.group }}"

- name: Install packages
  package:
    state: latest
    name:
      - unzip
      - net-tools
      - telnet
      - vim
      - java-11-openjdk-devel

- name: Ensure firewall is enabled
  service:
    name: firewalld
    enabled: true
    state: started
  tags:
  - firewall

- name: Configure firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ ports }}"
  tags:
  - firewall