unit:
  name: datagrid
  description: Red Hat Data Grid

console_users:
  admin: redhat-123
  developer: developer

service:
  user: "{{ unit.name }}"
  group: "{{ unit.name }}"

install_dir: "/opt/{{ unit.name }}"

ports:
  - 11222/tcp  # cache endpoint
  - 7800/tcp   # site clustering
  - 7801/tcp   # cross site TCP
  - 2157/tcp   # asym encryption

xsite_ssl:
  mode: asym
  dir: .
  name: xsite.jks
  alias: xsite
  key_password: changeit
  store_password: changeit
  type: JCEKS
  alg: Blowfish
  size: 56